import "./globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/react-data-grid@7.0.0-beta.46/lib/styles.min.css" />
  </head>
      <body>{children}</body>
    </html>
  )
}
